version: '3.2'

networks:
  integration-test-sandbox:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test

    depends_on:
      - db
    networks:
      - integration-test-sandbox
  db:
    image: postgres:12.12
    environment:
      POSTGRES_DB: it-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: on-failure
    networks:
      - integration-test-sandbox